Initial code reorganization
sidratresearch/tables_io pull request #1
Opened 2024-12-18 17:47 UTC by jscora

This PR reorganizes some files into folders. These files should then be split up into multiple files for future iterations. Additionally, testUtils was moved to the tests folder.

2025-01-06 16:52 UTC, mubdi requested changes
Quick removal of test file.

2025-01-06 16:52 UTC, mubdi commented on test_outmd.parquet
Should be removed

2025-01-07 15:24 UTC, jscora commented on test_outmd.parquet
File has been removed

2025-01-07 20:22 UTC, mubdi approved these changes
LGTM!

2025-01-07 20:22 UTC, merged